//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSchedule
    {
        public int ScheduleID { get; set; }
        public int MovieID { get; set; }
        public int TheaterID { get; set; }
        public System.DateTime StartDateAndTime { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Theater Theater { get; set; }
    }
}
